### ISSUE TITLE
when tram track/road are connecting with other road. Parts of the intersection have a missing texture.

### ISSUE THREAD

**Issue by tommargar** [Killface1980/RoadsUnited_Core#3]
when tram track/road are connecting with other road. Parts of the intersection have a missing texture.
http://steamcommunity.com/sharedfiles/filedetails/?id=649744176

**Comment by Unlawful-Productions** [comment]
Is this dependent on the zoom? Also would it be the lod? What what you can dig up on mod tools.

**Comment by tommargar** [comment]
I had this issue occasionally myself when first using adding the hook in January, and now it pops up again after re-integrating the hook, so I bet it has something to do with the hook.

It appeared on every zoom level, the lod was unrelated (changed the values ingame with modtools)

Another guy mentioned that only on Boreal maps this happens, but I couldn't reproduce.

Here's the mod list by the guy who posted the screenshot. https://gist.github.com/anonymous/795e188b323e89a2fe9a

I guess there is one mod making problems, cause I've cleaned my mod list since January.

I have no idea what happens when the hook is deployed, I tend to deactivate it as long as it is not needed by American Infrastructure.

**Comment by Unlawful-Productions** [comment]
I had this to the extreme after snowfall. Try disabling the node overrides temporarily. I really think the answer is in mod tools. Use the road customizer to selects nodes. Then pull up mod tools>tool controller>hovernode_I'd( by hovering over the problem node).
The enter the node into net manager>msomethingnode buffer. Hope that helps.

**Comment by tommargar** [comment]
marcosbarauskas:
I have the same issue described by Kartoffelgnom. It seems that the glitch has the sky color, light during the day and dark at night.

**Comment by Unlawful-Productions** [comment]
Sorry for the absence, there's a metric fuck ton of textures I'm trying to push through and I is driving me nuts. Anyways, I see that this still seems to be an issue, have you tried fixing the node apr? If it's basically invisible, then the texture for that mesh name is not being loaded. You may need to add a redirect for the tram roads to either point to an actual node, or a substitution. Additionally, the if-check for the node in question should not be too specific (I had this problem when getting the oneway textures to load.). And finally, make sure the texture is the right size.

These APR's are driving me nuts. I've finally got a solid workflow and I will try recreating this problem soon.

Being redundant here, but maybe creating a new RoadSmallTramNode_MainTex and APRMap will solve the problem?

I keep going on with this because the node replacement code is very broad in its scope which is great for simplicity; but not so much for specific issues.

**Comment by tommargar** [comment]
the node which is used is the RoadSmallJunction; the apr maps are not the cause, when the hook is deactivated the bug is gone. Unfortunately I don't understand the code of the hook and so will leave it deactivated. I won't look any further into this issue.

**Comment by Unlawful-Productions** [comment]
That's fine. I'll look into it. I only need the texture hook to work for highways only anyways. No need to make it a catch all. I'm thinking of having it activated but only called in certain conditions. IE: Highways.

**Comment by tommargar** [comment]
disabled the hook for now as it's still causing problems I can't fix.
